applications/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.applications, name='applications'),
    path('addtoapplications/<int:id>', views.addtoapplications, name='addtoapplications'),
    path('deletefromapplications/<int:id>', views.deletefromapplications, name='deletefromapplications')
]

favorites/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.favorites, name='favorites'),
    path('addtofavorites/<int:id>', views.addtofavorites, name='addtofavorites'),
    path('deletefromfavorites/<int:id>', views.deletefromfavorites, name='deletefromfavorites'),
]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('homebase.html', views.homebase, name='index'),
    path('index.html', views.index, name='index'),
    path('header.html', views.header, name='header'),
    path('about.html', views.about, name='about'),
    path('blog.html', views.blog, name='blog'),
    path('blog-single.html', views.blog_single, name='blog-single'),
    path('contact.html', views.contact, name='contact'),
    path('faq.html', views.faq, name='faq'),
    path('gallery.html', views.gallery, name='gallery'),
    path('job-listings.html', views.job_listings, name='job-listings'),
    path('job-single.html', views.job_single, name='job-single'),
    path('login.html', views.login, name='login'),
    path('main.html', views.main, name='main'),
    path('portfolio.html', views.portfolio, name='portfolio'),
    path('portfolio-single.html', views.portfolio_single, name='portfolio-single'),
    path('post-job.html', views.post_job, name='post-job'),
    path('service-single.html', views.service_single, name='service-single'),
    path('services.html', views.services, name='services'),
    path('testimonials.html', views.testimonials, name='testimonials'),

]

isBul/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('isIlan', include('isIlan.urls')),
    path('home/', include('home.urls')),
    path('user/', include('user.urls')),
    path('favorites/', include('favorites.urls')),
    path('applications/', include('applications.urls')),
    path('', include('home.urls')),
    path(r'ckeditor/', include('ckeditor_uploader.urls')),
    path('search/', views.ilan_search, name='ilan_search'),
    path(r'search_auto/', views.ilan_search_auto, name='ilan_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('job_detail/<slug:slug>/<int:id>', views.job_detail, name='job_detail'),
    path('faq/', views.FAQ, name='faq'),
    path('myjobs/', views.myjobs, name='myjobs'),
    path('applicants/<int:id>', views.applicants, name='applicants'),
    path('applicant_profile/<int:id>', views.applicant_profile, name='applicant_profile'),
    path('applicants/accept/<int:id>', views.applicant_profile_accept, name='applicant_profile_accept'),
    path('applicants/decline/<int:id>', views.applicant_profile_decline, name='applicant_profile_decline'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from isIlan.models import Ilan


class Applications(models.Model):
    STATUS = (
        ('True', 'True'),
        ('Pending', 'Pending'),
        ('False', 'False'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    job = models.ForeignKey(Ilan, on_delete=models.SET_NULL, null=True)
    applicationDate = models.DateField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS, default='Pending')

    def jobPublisher(self):
        return self.job

    def jobName(self):
        return self.job.ilanBaslik

favorites/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from isIlan.models import Ilan


class Favorites(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    job = models.ForeignKey(Ilan, on_delete=models.SET_NULL, null=True)

    def jobPublisher(self):
        return self.job

    def jobName(self):
        return self.job.ilanBaslik

isIlan/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm
from django.urls import reverse
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Category(MPTTModel):
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    kategoriIsmi = models.CharField(max_length=50)
    slug = models.SlugField(blank=True, unique=True)

    class MPTTMeta:
        level_attr = 'mptt_level'
        order_insertion_by = ['kategoriIsmi']

    def __str__(self):
        full_path = [self.kategoriIsmi]
        k = self.parent
        while k is not None:
            full_path.append(k.kategoriIsmi)
            k = k.parent
        return ' / '.join(full_path[::-1])

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Ilan(models.Model):

    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )

    calismaZamaniSecenek = (
        ('Yarı Zamanlı', 'Yarı Zamanlı'),
        ('Tam Zamanlı', 'Tam Zamanlı'),
    )

    konumSecenek = (
        ('Tekirdağ', 'Tekirdağ'),
        ('İstanbul', 'İstanbul'),
        ('Ankara', 'Ankara'),
        ('İzmir', 'İzmir'),
        ('Karabük', 'Karabük'),
    )

    status = models.CharField(max_length=15, choices=STATUS, default=False)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    sirketPoster = models.ImageField(blank=True, upload_to='images/')
    email = models.CharField(max_length=50)
    ilanBaslik = models.CharField(max_length=50)
    konum = models.CharField(max_length=150, choices=konumSecenek)
    isTuru = models.ForeignKey(Category, on_delete=models.CASCADE)
    calismaZamani = models.CharField(max_length=150, choices=calismaZamaniSecenek, blank=True)
    isTanimi = RichTextUploadingField()
    genelNitelikler = RichTextUploadingField(default="default")
    sirketIsmi = models.CharField(max_length=50)
    tecrube = models.CharField(max_length=50, default="Tecrübesiz")
    personelSayisi = models.CharField(max_length=16, default="Belirtilmemiştir")
    etiketAlani = models.CharField(blank=True, max_length=150)
    sirketWebsite = models.CharField(blank=True, max_length=50)
    sirketFacebook = models.CharField(blank=True, max_length=50)
    sirketTwitter = models.CharField(blank=True, max_length=50)
    sirketLinkedin = models.CharField(blank=True, max_length=50)
    sirketLogo = models.ImageField(blank=True, upload_to='images/')
    slug = models.SlugField(blank=True, unique=True)
    sonBasvuru = models.DateField(default="2020-07-25")
    yayinTarihi = models.DateField(auto_now=True)

    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.sirketIsmi

    def get_absolute_url(self):
        return reverse('ilan_detail', kwargs={'slug': self.slug})


class Comment(models.Model):
    STATUS = (
        ('New', 'New'),
        ('True', 'True'),
        ('False', 'False'),
    )

    ilan = models.ForeignKey(Ilan, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(blank=True, max_length=50)
    comment = models.CharField(blank=True, max_length=250)
    status = models.CharField(max_length=15, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)

    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment']

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(label='search', max_length=100, required=False)
    category = forms.CharField(label='category', max_length=20, required=False)
    sehir = forms.CharField(label='sehir', max_length=20, required=False)


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=200)
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

applications/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from applications.models import Applications


def index(request):
    return HttpResponseRedirect('/applications.html')


@login_required(login_url='/login')
def addtoapplications(request, id):
    url = request.META.get('HTTP_REFERER')
    checkjob = Applications.objects.filter(job_id=id)
    if checkjob:
        messages.info(request, "İlan'a zaten başvurulmuş!")
        return HttpResponseRedirect(url)

    if id:
        current_user = request.user
        data = Applications()
        data.user_id = current_user.id
        data.job_id = id
        data.save()

        messages.success(request, "İlan'a başarı ile başvurulmuştur.")
        return HttpResponseRedirect(url)

    messages.warning(request, "İlan'a başvurulurken hata oluştu!!!")
    return HttpResponseRedirect(url)


@login_required(login_url='/login')
def deletefromapplications(request, id):
    url = request.META.get('HTTP_REFERER')
    Applications.objects.filter(job_id=id).delete()
    messages.success(request, "İlan listeden silinmiştir.")
    return HttpResponseRedirect(url)


@login_required(login_url='/login')
def applications(request):
    current_user = request.user
    applications = Applications.objects.filter(user_id=current_user.id)
    context = {
        'applications': applications
    }

    return render(request, 'applications.html', context)

favorites/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from favorites.models import Favorites
from isIlan.models import Ilan


def index(request):
    return HttpResponseRedirect('/favorites.html')


@login_required(login_url='/login')
def addtofavorites(request, id):
    url = request.META.get('HTTP_REFERER')
    checkjob = Favorites.objects.filter(job_id=id)
    if checkjob:
        return HttpResponseRedirect('/favorites/deletefromfavorites/' + str(id))

    if id:
        current_user = request.user
        data = Favorites()
        data.user_id = current_user.id
        data.job_id = id
        data.save()

        messages.success(request, "İlan başarı ile kaydedilmiştir.")
        return HttpResponseRedirect(url)

    messages.warning(request, "İlan kaydedilirken hata oluştu!!!")
    return HttpResponseRedirect(url)


@login_required(login_url='/login')
def deletefromfavorites(request, id):
    url = request.META.get('HTTP_REFERER')
    Favorites.objects.filter(job_id=id).delete()
    messages.success(request, "İlan listeden silinmiştir.")
    return HttpResponseRedirect(url)


@login_required(login_url='/login')
def favorites(request):
    current_user = request.user
    favorites = Favorites.objects.filter(user_id=current_user.id)
    context ={
        'favorites': favorites
    }
    return render(request, 'favorites.html', context)

home/templates/contact.html
{% extends "homebase.html" %}
{% block body %} {% include "content-contact.html" %} {% endblock %}

home/templates/content-about.html
    <!-- HOME -->
    {% load static %}
    <section class="section-hero overlay inner-page bg-image" style="background-image: url({% static 'images/hero_1.jpg' %});" id="home-section">
      <div class="container">
        <div class="row">
          <div class="col-md-7">
            <h1 class="text-white font-weight-bold">Hakkımızda</h1>
            <div class="custom-breadcrumbs">
              <a href="index.html">Ana Sayfa</a> <span class="mx-2 slash">/</span>
              <span class="text-white"><strong>Hakkımızda</strong></span>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="site-section pb-0">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6 mb-5 mb-lg-0">
            <a data-fancybox data-ratio="2" href="{{ setting.aboutusLink }}" class="block__96788">
              <span class="play-icon"><span class="icon-play"></span></span>
              <img src="{{ setting.aboutusPicture.url }}" alt="Image" class="img-fluid img-shadow">
            </a>
          </div>
          <div class="col-lg-5 ml-auto">
            <h2 class="section-title mb-3">{{ setting.aboutusTitle }}</h2>
            <p class="lead">{{ setting.aboutus }}</p>
            <p></p>
          </div>
        </div>
      </div>
    </section>

    <section class="site-section pt-0">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6 mb-5 mb-lg-0 order-md-2">
            <a data-fancybox data-ratio="2" href="{{ setting.aboutusLink2 }}" class="block__96788">
              <span class="play-icon"><span class="icon-play"></span></span>
              <img src="{{ setting.aboutusPicture2.url }}" alt="Image" class="img-fluid img-shadow">
            </a>
          </div>
          <div class="col-lg-5 mr-auto order-md-1  mb-5 mb-lg-0">
            <h2 class="section-title mb-3">{{ setting.aboutus2Title }}</h2>
            <p class="lead">{{ setting.aboutus2 }}</p>
          </div>
        </div>
      </div>
    </section>

    <section class="py-5 bg-image overlay-primary fixed overlay" id="next" style="background-image: url({% static 'images/hero_1.jpg' %});">
      <div class="container">
        <div class="row mb-5 justify-content-center">
          <div class="col-md-7 text-center">
            <h2 class="section-title mb-2 text-white">İŞBUL.COM</h2>
            <p class="lead text-white"></p>
          </div>
        </div>
        <div class="row pb-0 block__19738 section-counter">

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="{{ setting.calisanSayisi }}">0</strong>
            </div>
            <span class="caption">Çalışan</span>
          </div>

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="{{ setting.ofisSayisi }}">0</strong>
            </div>
            <span class="caption">Ofis</span>
          </div>

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="{{ setting.ozgecmisSayisi }}">0</strong>
            </div>
            <span class="caption">Özgeçmiş</span>
          </div>

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="{{ setting.uyeSirketSayisi }}">0</strong>
            </div>
            <span class="caption">Üye Şirket</span>
          </div>


        </div>
      </div>
    </section>

    <!--
    <section class="site-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-12 text-center" data-aos="fade">
            <h2 class="section-title mb-3">Our Team</h2>
          </div>
        </div>

        <div class="row align-items-center block__69944">

          <div class="col-md-6">
            <img src="{% static 'images/person_6.jpg' %}" alt="Image" class="img-fluid mb-4 rounded">
          </div>

          <div class="col-md-6">
            <h3>Elisabeth Smith</h3>
            <p class="text-muted">Creative Director</p>
            <p>Soluta quasi cum delectus eum facilis recusandae nesciunt molestias accusantium libero dolores repellat id in dolorem laborum ad modi qui at quas dolorum voluptatem voluptatum repudiandae voluptatibus ut? Ex vel  ad explicabo iure ipsa possimus consectetur neque rem molestiae eligendi velit?.</p>
            <div class="social mt-4">
              <a href="#"><span class="icon-facebook"></span></a>
              <a href="#"><span class="icon-twitter"></span></a>
              <a href="#"><span class="icon-instagram"></span></a>
              <a href="#"><span class="icon-linkedin"></span></a>
            </div>
          </div>

          <div class="col-md-6 order-md-2 ml-md-auto">
            <img src="{% static 'images/person_5.jpg' %}" alt="Image" class="img-fluid mb-4 rounded">
          </div>

          <div class="col-md-6">
            <h3>Chintan Patel</h3>
            <p class="text-muted">Creative Director</p>
            <p>Soluta quasi cum delectus eum facilis recusandae nesciunt molestias accusantium libero dolores repellat id in dolorem laborum ad modi qui at quas dolorum voluptatem voluptatum repudiandae voluptatibus ut? Ex vel  ad explicabo iure ipsa possimus consectetur neque rem molestiae eligendi velit?.</p>
            <div class="social mt-4">
              <a href="#"><span class="icon-facebook"></span></a>
              <a href="#"><span class="icon-twitter"></span></a>
              <a href="#"><span class="icon-instagram"></span></a>
              <a href="#"><span class="icon-linkedin"></span></a>
            </div>
          </div>
      </div>
    </section>
    -->

  </div>


  </body>
</html>

home/templates/content-applications.html
    <!-- HOME -->
    {% load static %}

    <section class="section-hero overlay inner-page bg-image" style="background-image: url({% static 'images/hero_1.jpg' %});" id="home-section">
      <div class="container">
        <div class="row">
          <div class="col-md-7">
            <h1 class="text-white font-weight-bold">Başvurularım</h1>
            <div class="custom-breadcrumbs">
              <a href="/">Ana Sayfa</a> <span class="mx-2 slash">/</span>
              <span class="text-white"><strong>Başvurularım</strong></span>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert" align="center">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <section class="site-section" id="next">
      <div class="container">

        {% if not applications %}
            <div class="row mb-5 justify-content-center">
              <div class="col-md-7 text-center">
                <h2 class="section-title mb-10">Başvurulan İlan Bulunamadı!</h2>
              </div>
            </div>
        {% endif %}

        <ul class="job-listings mb-5">
              {% for job in applications %}

                  <li class="job-listing d-block d-sm-flex pb-3 pb-sm-0 align-items-center">
                    <a href="/job_detail/{{ job.job.slug }}/{{ job.job.id }}"></a>
                    <div class="job-listing-logo">
                        <img src="{{ job.job.sirketLogo.url }}" alt="Image" class="img-fluid">
                    </div>

                    <div class="job-listing-about d-sm-flex custom-width w-100 justify-content-between mx-4">
                        <div class="job-listing-position custom-width w-50 mb-3 mb-sm-0">
                            <h2>{{ job.job.ilanBaslik }}</h2>
                            <strong>{{ job.job.sirketIsmi }}</strong>
                        </div>
                        <div class="job-listing-location mb-3 mb-sm-0 custom-width w-25">
                            <span class="icon-room"></span> {{ job.job.konum }}
                        </div>
                        <div class="job-listing-meta">
                            <span class="badge {% if job.status == "True"%}badge-success
                                               {% elif job.status == "Pending"%}badge-info
                                               {% else %}
                                               badge-danger
                                               {% endif %}">
                            {% if job.status == "True"%}
                                Onaylandı
                            {% elif job.status == "Pending"%}
                                Onay Bekliyor
                            {% else %}
                                Reddedildi
                            {% endif %}</span>
                        </div>
                    </div>

                  </li>

              {% endfor %}

        </ul>
      </div>
    </section>

  </body>
</html>

home/templates/content-contact.html
    <!-- HOME -->
{% load static %}
    <section class="section-hero overlay inner-page bg-image" style="background-image: url({% static 'images/hero_1.jpg' %});" id="home-section">
      <div class="container">
        <div class="row">
          <div class="col-md-7">
            <h1 class="text-white font-weight-bold">İletişim</h1>
            <div class="custom-breadcrumbs">
              <a href="index.html">Ana Sayfa</a> <span class="mx-2 slash">/</span>
              <span class="text-white"><strong>İletişim</strong></span>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert" align="center">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <section class="site-section" id="next-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 mb-5 mb-lg-0">

            <form action="" method="post" class="">
              <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="fname">İsim</label>
                    {{ form.fname }}
                </div>
                <div class="col-md-6">
                  <label class="text-black" for="lname">Soyisim</label>
                    {{ form.lname }}
                </div>
              </div>

              <div class="row form-group">

                <div class="col-md-12">
                  <label class="text-black" for="email">Email</label>
                  {{ form.email }}
                </div>
              </div>

              <div class="row form-group">

                <div class="col-md-12">
                  <label class="text-black" for="subject">Konu</label>
                  {{ form.subject }}
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <label class="text-black" for="message">Mesaj</label>
                  {{ form.message }}
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                    {% csrf_token %}
                  <input type="submit" value="Gönder" class="btn btn-primary btn-md text-white">
                </div>
              </div>


            </form>
          </div>
          <div class="col-lg-5 ml-auto">
            <div class="p-4 mb-3 bg-white">
              <p class="mb-0 font-weight-bold">Adres:</p>
              <p class="mb-4">{{ setting.address|safe }}</p>

              <p class="mb-0 font-weight-bold">Telefon:</p>
              <p class="mb-4"><a href="#">{{ setting.phone }}</a></p>

              <p class="mb-0 font-weight-bold">Email Adresi:</p>
              <p class="mb-0"><a href="#"></a>{{ setting.smtpemail }}</p>

            </div>
          </div>
        </div>
      </div>
    </section>

<!--
    <section class="site-section bg-light">
      <div class="container">
        <div class="row mb-5">
          <div class="col-12 text-center" data-aos="fade">
            <h2 class="section-title mb-3">Happy Candidates Says</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <div class="block__87154 bg-white rounded">
              <blockquote>
                <p>&ldquo;Ipsum harum assumenda in eum vel eveniet numquam cumque vero vitae enim cupiditate deserunt eligendi officia modi consectetur. Expedita tempora quos nobis earum hic ex asperiores quisquam optio nostrum sit&rdquo;</p>
              </blockquote>
              <div class="block__91147 d-flex align-items-center">
                <figure class="mr-4"><img src="{% static 'images/person_1.jpg' %}" alt="Image" class="img-fluid"></figure>
                <div>
                  <h3>Elisabeth Smith</h3>
                  <span class="position">Creative Director</span>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="block__87154 bg-white rounded">
              <blockquote>
                <p>&ldquo;Ipsum harum assumenda in eum vel eveniet numquam, cumque vero vitae enim cupiditate deserunt eligendi officia modi consectetur. Expedita tempora quos nobis earum hic ex asperiores quisquam optio nostrum sit&rdquo;</p>
              </blockquote>
              <div class="block__91147 d-flex align-items-center">
                <figure class="mr-4"><img src="{% static 'images/person_2.jpg' %}" alt="Image" class="img-fluid"></figure>
                <div>
                  <h3>Chris Peter</h3>
                  <span class="position">Web Designer</span>
                </div>
              </div>
            </div>
          </div>


        </div>
      </div>
    </section>
-->

  </div>

  </body>
</html>

home/templates/content-index.html
    <!-- HOME -->
    {% load static %}
  </div>


  </body>
</html>

home/templates/content-job-listings.html
    <!-- HOME -->
    {% load static %}
    {% csrf_token %}
    <section class="site-section" id="next">
      <div class="container">

        <div class="row mb-5 justify-content-center">
          <div class="col-md-7 text-center">
            <h2 class="section-title mb-2">{{ sayi }} Sonuç Bulundu</h2>
          </div>
        </div>

        <ul class="job-listings mb-5">



              {% for rs in ilanlar %}

                  <li class="job-listing d-block d-sm-flex pb-3 pb-sm-0 align-items-center">
                    <a href="/job_detail/{{ rs.slug }}/{{ rs.id }}"></a>
                    <div class="job-listing-logo">
                        <img src="{{ rs.sirketLogo.url }}" alt="Image" class="img-fluid">
                    </div>

                    <div class="job-listing-about d-sm-flex custom-width w-100 justify-content-between mx-4">
                        <div class="job-listing-position custom-width w-50 mb-3 mb-sm-0">
                            <h2>{{ rs.ilanBaslik }}</h2>
                            <strong>{{ rs.sirketIsmi }}</strong>
                        </div>
                        <div class="job-listing-location mb-3 mb-sm-0 custom-width w-25">
                            <span class="icon-room"></span> {{ rs.konum }}
                        </div>
                        <div class="job-listing-meta">
                            <span class="badge
                            {% if rs.calismaZamani == "Tam Zamanlı"%}
                                badge-success
                            {% endif %}
                            {% if rs.calismaZamani == "Yarı Zamanlı" %}
                                badge-danger
                            {% endif %}
                        ">{{ rs.get_calismaZamani_display }}</span>
                        </div>
                    </div>

                  </li>

              {% endfor %}



        </ul>

        <div class="row pagination-wrap">
          <div class="col-md-6 text-center text-md-left mb-4 mb-md-0">
            <span>Showing 1-7 Of {{ sayi }} Jobs</span>
          </div>
          <div class="col-md-6 text-center text-md-right">
            <div class="custom-pagination ml-auto">
              <a href="#" class="prev">Geri</a>
              <div class="d-inline-block">
              <a href="#" class="active">1</a>
              <a href="#">2</a>
              <a href="#">3</a>
              <a href="#">4</a>
              </div>
              <a href="#" class="next">İleri</a>
            </div>
          </div>
        </div>

      </div>
    </section>



  </body>
</html>

home/templates/favorites.html
{% extends "homebase.html" %}
{% block body %} {% include "content-favorites.html" %} {% endblock %}

home/templates/job-listings.html
{% extends "homebase.html" %}
{% block search %} {% include "section-search-small.html" %} {% endblock %}
{% block body %} {% include "content-job-listings.html" %} {% endblock %}
{% block lookingForAJob %} {% include "section-looking-for-a-job.html" %} {% endblock %}

home/templates/service-single.html
{% extends "homebase.html" %}
{% block body %} {% include "content-service-single.html" %} {% endblock %}

home/templates/testimonials.html
{% extends "homebase.html" %}
{% block body %} {% include "content-testimonials.html" %} {% endblock %}